services:
  simbricks-dev:
    image: simbricks/simbricks:latest
    container_name: simbricks-workspace
    stdin_open: true
    tty: true
    working_dir: /workspace
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - .:/workspace
      - simbricks-history:/root/.bash_history_dir
    environment:
      - HISTFILE=/root/.bash_history_dir/.bash_history

volumes:
  simbricks-history:
